-- {"id":172006,"ver":"1.0.0","libVer":"1.0.0","author":"felipebonfim2006","dep":["Madara=2.9.0"]}

return Require("Madara")("https://kiniga.com", {
    id = 172006,
    name = "Kiniga",
    imageURL = "https://www.kiniga.com/wp-content/uploads/2017/10/New-Logo-Inv-150px.png",

    latestNovelSel = "div.col-6.col-md-2.badge-pos-2",
    novelListingURLPath = "projetos",
    shrinkURLNovel = "projeto",
    hasSearch = true,
    ajaxUsesFormData = true,
    genres = {
    "action",
    "artes-marciais",
    "aventura",
    "comedia",
    "contemporaneo",
    "contos-originais",
    "crime",
    "cyberpunk",
    "destaque",
    "distopia",
    "drama",
    "ecchi",
    "espacial",
    "esportes",
    "fanfic",
    "fantasia",
    "ficcao-cientifica",
    "gastronomia",
    "harem",
    "historico",
    "horror",
    "infantil",
    "isekai",
    "jogos",
    "lgbt",
    "magia",
    "mecha",
    "medieval",
    "militar",
    "misterio",
    "mitologia",
    "moderno",
    "pos-apocaliptico",
    "psicologico",
    "realidade-virtual",
    "recomendado",
    "romance",
    "rpg",
    "sci-fi",
    "seinen",
    "shounen",
    "sistema-de-jogo",
    "slice-of-life",
    "snkhome",
    "sobrenatural",
    "somente-na-kiniga",
    "suspense",
    "terror",
    "terror-psicologico",
    "traducoes",
    "tragedia",
    "urbano",
    "vida-escolar"
}
})
