-- {"id":95564,"ver":"2.0.10","libVer":"1.0.0","author":"Bigrand, Confident-hate","dep":["novelvault>=1.0.0"]}

return Require("novelvault")("https://novelbin.com", {
	id = 95564,
	name = "NovelBin",
	imageURL = "https://shosetsuorg.gitlab.io/extensions/icons/NovelBin.png",

	authorParam = "a",
	genreSpace = "-",
	ajaxChaptersURL = "ajax/chapter-archive",

	searchImgModFunc = function(imageURL)
		return imageURL:gsub("_80_113", "")
	end,

	listingConfigs = {
		{ name = "Hot Novel", incrementing = true, param = "sort/top-hot-novel" },
		{ name = "Most Popular", incrementing = true, param = "sort/top-view-novel" },
		{ name = "Completed Novel", incrementing = true, param = "sort/completed" },
		{ name = "Ongoing Novel", incrementing = true, param = "sort/ongoing" },
		{ name = "Latest Release", incrementing = true, param = "sort/latest" },
	},

	supportedFilters = { "genre", "author", "status", "tag" },

	statuses = {
		{ name = "Ongoing",   param = "sort/ongoing" },
		{ name = "Completed", param = "sort/completed" },
    },

	genres = {
		"Action",
		"Adult",
		"Adventure",
		"Anime & Comics",
		"Comedy",
		"Drama",
		"Eastern",
		"Ecchi",
		"FanFiction",
		"Fantasy",
		"Game",
		"Gender Bender",
		"Harem",
		"Historical",
		"Horror",
		"Isekai",
		"Josei",
		"LGBT+",
		"LitRPG",
		"Magic",
		"Magical Realism",
		"Martial Arts",
		"Mature",
		"Mecha",
		"Modern Life",
		"Mystery",
		"Other",
		"Psychological",
		"Reincarnation",
		"Romance",
		"School Life",
		"Sci-Fi",
		"Seinen",
		"Shoujo",
		"Shoujo AI",
		"Shounen",
		"Shounen AI",
		"Slice of life",
		"Smut",
		"Sports",
		"Supernatural",
		"System",
		"Thriller",
		"Tragedy",
		"Urban",
		"Urban Life",
		"Video Games",
		"War",
		"Wuxia",
		"Xianxia",
		"Xuanhuan",
		"Yaoi",
		"Yuri",
	}
})
