-- {"id":2,"ver":"4.2.0","libVer":"1.0.0","author":"Bigrand, Doomsdayrs","dep":["novelvault>=1.0.0"]}

return Require("novelvault")("https://novlove.com", {
	id = 2,
	name = "NovLove (Boxnovel)",
	imageURL = "https://shosetsuorg.gitlab.io/extensions/icons/NovLove.png",

	novelParam = "novel",
	authorParam = "nov-love-author",
	genreParam = "nov-love-genres",
	genreSpace = "-",
	ajaxChaptersURL = "ajax/chapter-archive",

	searchImgModFunc = function(imageURL)
		return imageURL:gsub("_80_113", "")
	end,

	listingConfigs = {
		{ name = "Hot Novel", incrementing = true, param = "sort/nov-love-hot" },
		{ name = "Most Popular", incrementing = true, param = "sort/nov-love-popular" },
		{ name = "Completed Novel", incrementing = true, param = "sort/nov-love-complete" },
		{ name = "Ongoing Novel", incrementing = true, param = "sort/nov-love-ongoing" },
		{ name = "Latest Release", incrementing = true, param = "sort/nov-love-daily-update" },
	},

	supportedFilters = { "genre", "author", "status", "tag" },

	statuses = {
		{ name = "Ongoing",   param = "sort/nov-love-ongoing" },
		{ name = "Completed", param = "sort/nov-love-complete" },
	},

	genres = {
		"Action",
		"Adult",
		"Adventure",
		"Anime & Comics",
		"Comedy",
		"Drama",
		"Eastern",
		"Ecchi",
		"Fan-Fiction",
		"FanFiction",
		"Fantasy",
		"Game",
		"Gender Bender",
		"Harem",
		"Historical",
		"Horror",
		"Isekai",
		"Josei",
		"LGBT+",
		"LitRPG",
		"Magic",
		"Magical Realism",
		"Martial Arts",
		"Mature",
		"Mecha",
		"Modern Life",
		"Mystery",
		"Other",
		"Psychological",
		"Reincarnation",
		"Romance",
		"School Life",
		"Sci-Fi",
		"Seinen",
		"Shoujo",
		"Shoujo AI",
		"Shounen",
		"Shounen AI",
		"Slice of life",
		"Smut",
		"Sports",
		"Supernatural",
		"System",
		"Thriller",
		"Tragedy",
		"Urban",
		"Urban Life",
		"Video Games",
		"War",
		"Wuxia",
		"Xianxia",
		"Xuanhuan",
		"Yaoi",
		"Yuri",
	}
})
