-- {"id":111359,"ver":"1.0.0","libVer":"1.0.0","author":"Bigrand","dep":["novelvault>=1.0.0"]}

return Require("novelvault")("https://novgo.net", {
	id = 111359,
	name = "Novgo (NET)",
	imageURL = "https://shosetsuorg.gitlab.io/extensions/icons/NovgoNET.png",

	listingConfigs = {
		{ name = "Hot Novel", incrementing = true, param = "hot-novel" },
		{ name = "Most Popular", incrementing = true, param = "most-popular" },
		{ name = "Completed Novel", incrementing = true, param = "completed-novel" },
		{ name = "Ongoing Novel", incrementing = true, param = "status/Ongoing" },
		{ name = "Latest Release", incrementing = true, param = "latest-release-novel" },
	},

	supportedFilters = { "genre", "author", "status" },

	statuses = {
        { name = "Ongoing",   param = "status/Ongoing" },
        { name = "Completed", param = "completed-novel" },
	},

	genres = {
		"Action",
		"Adult",
		"Adventure",
		"Comedy",
		"Drama",
		"Eastern",
		"Ecchi",
		"Fantasy",
		"Game",
		"Gender Bender",
		"Harem",
		"Hentai",
		"Historical",
		"Horror",
		"Isekai",
		"Josei",
		"LGBT+",
		"Lolicon",
		"Magic",
		"Magical",
		"Magical Realism",
		"Manhua",
		"Martial",
		"Martial Arts",
		"Mature",
		"Mecha",
		"Mystery",
		"Psychological",
		"Reincarnation",
		"Romance",
		"School Life",
		"Sci-fi",
		"Seinen",
		"Shoujo",
		"Shoujo AI",
		"Shounen",
		"Shounen AI",
		"Slice of Life",
		"Smut",
		"Sports",
		"Supernatural",
		"System",
		"Traged",
		"Tragedy",
		"Video Games",
		"Wuxia",
		"Xianxia",
		"Xuanhuan",
		"Yaoi",
		"Yuri",
	}
})
